web_site:
  resource: "@WebSiteBundle/Controller"
  type:     annotation


hello:
    path:     /hello/{name}
    defaults:
       _controller: EduardTrayanWebsiteBundle:Hello:index































    #template: 'WebSiteBundle:Index:about.html.twig'